---

- name: get vm info
  hosts: all
  gather_facts: yes

  tasks:
    - debug:
        var: ansible_facts

    - debug:
        var: ansible_distribution

    - debug:
        var: tags.Stage

    - debug:
        var: kernel

    - debug:
        msg: "foo"
      when: kernel is version('4.18.0', '<')