---

- name: get vm info
  hosts: all
  gather_facts: yes

  tasks:
    - name: List information
      debug:
        msg: "{{ ansible_play_hosts \
          | map('extract', hostvars) \
          | list \
          | json_query('[*].{tags_Name: tags.Name \
            tags_Platform: tags.Platform \
            tags_Tier: tags.Tier \
            tags_Zone: tags.Zone \
            tags_Stage: tags.Stage \
            inventory_hostname: inventory_hostname \
            }') }}"
      run_once: yes


