---

- name: get vm info
  hosts: all
  gather_facts: yes

  tasks:
    - name: List information
      debug:
        msg: "{{ ansible_play_hosts \
          | map('extract', hostvars) \
          | list \
          | json_query('[*].{tags_Name: tags.Name \
            tags_Platform: tags.Platform \
            tags_Tier: tags.Tier \
            tags_Zone: tags.Zone \
            ,name: inventory_hostname}') }}"
      run_once: yes

    - debug:
        var: ansible_distribution

    - debug:
        var: tags.Stage

